version: "3.9"
name: news-sentiment-pipeline
networks:
  redpanda_network:
    external: true
    name: redpanda_network

services:

  news:
    build:
      context: ../services/news
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/news/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    # restart: always

  sentiment:
    build:
      context: ../services/sentiment
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/sentiment/settings.env
      - ../services/sentiment/credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - MODEL_PROVIDER=openai
    # restart: always

  to-feature-store:
    build:
      context: ../services/to-feature-store
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/to-feature-store/live.settings.sentiment.env
      - ../services/to-feature-store/credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    # restart: always